version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_go
    ports:
      - "9055:9055"
    environment:
      - bd=postgres://postgres:123@10.160.2.96:5433/mydb
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge