---
- name: Copy project to remote host
  hosts: app_host
  tasks:
    - name: Create project directory on remote
      file:
        path: "/home/schweppa/work/postgres/postgres/"
        state: directory
        mode: '0755'

    - name: Copy project source code
      synchronize:
        src: "{{ playbook_dir }}/../../postgres/postgres/"
        dest: "/home/schweppa/work/postgres/postgres/"
 