---
- name: Create app directory
  file:
    path: "{{ project_path }}"
    state: directory
    mode: '0755'

- name: Copy project source code
  synchronize:
    src: "/home/schweppa/work/postgres/postgres/"
    dest: "{{ project_path }}/"
    checksum: yes
  when: ansible_connection != "local"

- name: Copy docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_path }}/postgres/docker-compose.yml"
    mode: '0644'

- name: Start containers
  command:
    cmd: docker compose up -d
    chdir: "{{ project_path }}/postgres"
  tags: [start]

- name: Stop containers
  command:
    cmd: docker compose down
    chdir: "{{ project_path }}/postgres"
  tags: [stop, never]

- name: Recreate
  command:
    cmd: docker compose up -d --force-recreate
    chdir: "{{ project_path }}/postgres"
  tags: [restart, never]