---
- name: Create project directory on remote
  file:
    path: "{{ project_path }}"
    state: directory
    mode: '0755'

- name: Copy project source code to remote
  synchronize:
    src: "{{ playbook_dir }}/../../postgres/postgres/"
    dest: "{{ project_path }}/"
    checksum: yes
  when: ansible_connection != "local"

- name: Copy docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_path }}/docker-compose.yml"
    mode: '0644'
  tags: [config]

- name: Start containers
  command:
    cmd: docker compose up -d
    chdir: "{{ project_path }}"
  tags: [start]

- name: Stop containers
  command:
    cmd: docker compose down
    chdir: "{{ project_path }}"
  tags: [stop, never]