---
project_path: "/home/{{ ansible_user }}/work/postgres/postgres"
app_name: "myapp"
app_port: 9055


db_project_path: "/home/{{ ansible_user }}/work/postgres/db"
db_container_name: "postgres"
db_port: 5433
db_user: "postgres"
db_name: "mydb"
db_host: "172.17.0.1"